alloc8or/gta5-nativedb-data

natives.json
- Updated some ped weapon ammo related native info & params. (Did some renaming as well)
- Updated GET_VARIANT_COMPONENT, _GET_VARIANT_PROP and GET_FORCED_PROP with the proper types and better names.
- Updated return type & first parameter of GET_SHOP_PED_APPAREL_FORCED_PROP_COUNT.
- Updated DOES_SHOP_PED_APPAREL_HAVE_RESTRICTION_TAG.
Renames:
- **_GET_MAX_AMMO_2** renamed to **_GET_MAX_AMMO_BY_TYPE**
- **_ADD_PED_AMMO** renamed to **_ADD_AMMO_TO_PED_BY_TYPE**
=> Ammo & clothing native improvements

natives.json
Another misleading/wrong description of functionality
=> Update GET_VEHICLE_PED_IS_IN's BOOL param

natives.json
Add Informations for Int, Bool, Float, Mask Bool, Mask Int Stat Native
=> More informations for stat native

natives.json
replay_controller uses 0-7, but I couldn't see any changes with 4 and 5
=> Update vehicle windowIndex values

natives.json
just discovered the p10 parameter on ADD_ROPE is the winding speed used by START_ROPE_WINDING.
=> ADD_ROPE: renamed parameter p10 to windingSpeed + description

natives.json
Just walked through all 59 natives that point to the same nullsub
=> Annotate 2 more nullsub natives

natives.json
Diff from the old paste:
```diff
29a30
> bokeh_removebuzz
40a42
> CarDamageHit
45a48,50
> CarPitstopComplete
> CarPitstopHealth01
> CarPitstopHealth02
47a53,62
> casino_brightroom
> casino_hotel
> Casino_Lightsoff
> casino_main_floor_heist
> casino_mainfloor
> casino_mainWhiteFloor
> casino_managementlobby
> casino_managementOff
> casino_managersoffice
> CasinoBathrooms
51a67
> Chop
65a82
> DEFAULT
67a85,86
> dlc_casino_carpark
> DLC_Casino_Garage
156a176
> Heist_VaultGas01
192a213
> int_01_blackbox
326a348,354
> mp_arc_planning_entity_ambient
> MP_Arcade_Derelict
> MP_Arcade_Hipster
> MP_Arcade_Planning_Pre
> MP_Arcade_Planning_Room
> MP_Arcade_Retro
> MP_Arcade_Tunnel
371a400,432
> MP_casino_apartment_bar
> MP_casino_apartment_barPARTY
> MP_casino_apartment_barPARTY_0
> …
```
=> Update timecycle modifiers list

natives.json
Based on the values used in the scripts: https://github.com/Sainan/GTA-V-Decompiled-Scripts/commit/fe6910cf4ef6ed4fe8ca141c7bb47c9082144d96
=> Update TASK_LOOK_AT_COORD's duration param type

natives.json
Research & informations I have collected, credits to various people that helped or contributed on some channels
=> Document various natives and improve documentation on existing natives

natives.json
Definitely not the best comments but I will update them if there are suggestions.
=> Document some FILES natives

natives.json
Added firing patterns links to `TASK_SHOOT_AT_ENTITY` and `TASK_SHOOT_AT_COORD`
=> Add firing patterns links

natives.json
=> miscellaneous 323 findings

natives.json
=> SET_VEHICLE_INDIVIDUAL_DOORS_LOCKED

natives.json
func_3079() on freemode.ysc (Line 257273)
=> added new native, belongs to NETWORK namespace

natives.json
Inferred names primarily from tty scripts. Other potential names:
```
0xE84EB93729C5F36A = _GET_OBJECT_TINT
0x971DA0055324D033 = _SET_OBJECT_TINT
```
=> miscellaneous

natives.json
_0xF60165E1D2C5370B -> _GET_PED_MOVEMENT_SPEED
_0x44621483FF966526 -> _SET_CHECKPOINT_ICON_SCALE
_0x394BDE2A7BBA031E -> _HAS_ENTITY_CLEAR_LOS_TO_ENTITY_2
=> misc natives

natives.json
Updated `TASK_HELI_MISSION` documentation 
- Fixed type for `unk3` parameter
- Changed parameter names to be more accurate
- Thoroughly revised notes to reflect recent research
=> Updated TASK_HELI_MISSION documentation

natives.json
Just some random param types I found while researching.
All found in 2372 code
=> Add some random findings

natives.json
More random stuff I found while researching
=> Some more random findings

natives.json
"Name" is a bit ambigious, so the comment confused me a bit. I feel it could also just have no comment at all.
=> Update GET_RADIO_STATION_NAME's comment

natives.json
=> changed weird comment

natives.json
NetCash + UGC + few session-related things
=> assorted 323 natives

natives.json
Fix FIND_SPAWN_POINT_IN_DIRECTION arguments and cleanup documentation
=> Fix FIND_SPAWN_POINT_IN_DIRECTION

natives.json
Adds various natives related direct-links to data in my open source repository that I keep updating every GTA 5 update
=> Add links with updated/complete list of related data

natives.json
added param types and some information about this native
=> added TASK_RAPPEL_DOWN_WALL arg types & names and comment

natives.json
I initially misunderstood your comment because I just woke up, but these changes should avoid confusion.
=> Update 0x5C707A667DF8B9FA and 0x0EDE326D47CD0F3E
